workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build iOS Simulator
        script: flutter build ios --simulator
        working_directory: frontend/kinoapay_app
      - name: Package Simulator App
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
        working_directory: frontend/kinoapay_app
    artifacts:
      - frontend/kinoapay_app/build/ios/ipa/Runner.app.zip
