workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter build ios --simulator
      - mkdir -p frontend/kinoapay_app/build/ios/ipa
      - zip -r frontend/kinoapay_app/build/ios/ipa/Runner.app.zip frontend/kinoapay_app/build/ios/iphonesimulator/Runner.app
    artifacts:
      - frontend/kinoapay_app/build/ios/ipa/Runner.app.zip